name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        arch: [amd64, arm64]
        include:
          - arch: amd64
            build_arg: amd64
          - arch: arm64
            build_arg: arm64

    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: arm64

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        platforms: linux/amd64,linux/arm64
        build-args: |
          ARCH=${{ matrix.build_arg }}
        tags: |
          ghcr.io/jiechau/ppp:${{ matrix.arch }}

  create-manifest: # This is the new step to create and push the manifest list
    runs-on: ubuntu-latest
    needs: build-and-push # Wait for all builds to finish
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Create and push manifest list for latest and 3.9
        run: |
          docker manifest create ghcr.io/jiechau/ppp:latest ghcr.io/jiechau/ppp:amd64 ghcr.io/jiechau/ppp:arm64
          docker manifest push ghcr.io/jiechau/ppp:latest
          docker manifest create ghcr.io/jiechau/ppp:3.9 ghcr.io/jiechau/ppp:amd64 ghcr.io/jiechau/ppp:arm64
          docker manifest push ghcr.io/jiechau/ppp:3.9
