name: Build and Push Docker Images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IMAGE_NAME: ghcr.io/jiechau/ppp

jobs:

  build-and-push:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        arch: [amd64, arm64]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Install Git LFS
      run: |
        sudo apt-get install git-lfs
        git lfs install
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        platforms: linux/${{ matrix.arch }}
        push: true
        tags: |
          ${{ env.IMAGE_NAME }}:${{ matrix.arch }}
          ${{ env.IMAGE_NAME }}:latest
          ${{ env.IMAGE_NAME }}:3.9
        build-args: |
          ARCH=${{ matrix.arch }}
          
  push-manifest:
    needs: build-and-push
    
    runs-on: ubuntu-latest
    
    steps:
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Push manifest
      run: |
        docker manifest create ghcr.io/jiechau/ppp:latest \
          --amend ghcr.io/jiechau/ppp:amd64 \
          --amend ghcr.io/jiechau/ppp:arm64
        
        docker manifest push ghcr.io/jiechau/ppp:latest
        
        docker manifest create ghcr.io/jiechau/ppp:3.9 \
          --amend ghcr.io/jiechau/ppp:amd64 \
          --amend ghcr.io/jiechau/ppp:arm64
          
        docker manifest push ghcr.io/jiechau/ppp:3.9