name: Build and Push Docker Images

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: [amd64, arm64]
        include:
          - arch: amd64
            platform: linux/amd64
          - arch: arm64
            platform: linux/arm64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true  # Enable LFS

      - name: Install Git LFS
        run: |
          sudo apt-get update
          sudo apt-get install git-lfs
          git lfs install

      - name: Pull LFS files
        run: git lfs pull

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/jiechau/ppp:${{ matrix.arch }}
          platforms: ${{ matrix.platform }}
          build-args: |
            ARCH=${{ matrix.arch }}

      - name: Create and push multi-arch manifests
        run: |
          docker manifest create ghcr.io/jiechau/ppp:latest \
            --amend ghcr.io/jiechau/ppp:amd64 \
            --amend ghcr.io/jiechau/ppp:arm64
          docker manifest create ghcr.io/jiechau/ppp:3.9 \
            --amend ghcr.io/jiechau/ppp:amd64 \
            --amend ghcr.io/jiechau/ppp:arm64
          docker manifest push ghcr.io/jiechau/ppp:latest
          docker manifest push ghcr.io/jiechau/ppp:3.9
